version: "3"
services:
  worker1:
    build:
      context: ./worker_node
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8787:8080"
    environment:
       - FLASK_APP=client
       - FLASK_ENV=development

    volumes:
      - ./worker_node:/app





